### ISSUE TITLE
TabletopTableDetector pipeline parameters ignored

### ISSUE THREAD

**Issue by corot** [wg-perception/tabletop#23]
I noticed that if you remove the tabletop_detector/clusterer dictionary level, it works. E.g.
```
pipeline1:
  type: TabletopTableDetector
  module: 'object_recognition_tabletop'
  inputs: [source1]
  outputs: [sink1]
  parameters:
    # table detector
    min_table_size: 5000
    plane_threshold: 0.01
    table_cluster_tolerance: 0.01
    vertical_frame_id: '/map'
    # clusterer
    z_crop: 0.25  # The amount to keep in the z direction relative to the coordinate frame defined by the pose (def. 0.5)
    z_min:  0.002 # The amount to crop above the plane, in meters (def. 0.0075)
    cluster_distance: 0.01  # The maximum distance between a point and the cluster it belongs to (def. 0.02)
    min_cluster_size: 300   # Min number of points for a cluster (def. 300)
```
